
# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dataSensor_test

# development:
#   <<: *default
#   database: db/development.sqlite3

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dataSensor_development

production:
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>